# Generated by Django 2.1.7 on 2019-08-14 19:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190814_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='punlished_date',
            new_name='published_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 19, 51, 13, 977856, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 19, 51, 13, 977856, tzinfo=utc)),
        ),
    ]
